import type { Metadata } from "next";
import { Epilogue } from "next/font/google";  // Importing the Epilogue font
import "./globals.css";
import { getServerSession } from "next-auth";
import { options } from "../../../api/auth/[...nextauth]/options";
import AuthProvider from "@/lib/auth-provider";
import Verify from "@/lib/verify-user";
// Importing the Epilogue font from Google Fonts with all weights and italics
const epilogue = Epilogue({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);
  return (
    <AuthProvider session={session}>    
    <html lang="en">
      <body className={epilogue.className}>
      <Verify/>
        {children}</body>  {/* Apply Epilogue font */}
    </html>
    </AuthProvider>
  );
}
