import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import AuthProvider from "@/lib/auth-provider";
import Verify from "@/lib/verify-user";

const epilogue = Epilogue({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(options);

  return (
    <html lang="en">
      <body className={epilogue.className}>
        <AuthProvider session={session}>
          {/* <Verify /> */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
